version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-sid

    working_directory: ~/repo
    
    steps:
      - checkout

      - run:
          name: Maven Install
          command: mvn install --show-version --batch-mode --errors